apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-basic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git@github.com:dbastianelli/argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
